Keyboard goes down on opening nav drawer
openMF/android-client pull request #1554
Opened 2020-09-19 10:09 UTC by sachin-0102

Fixes #1549 

- [✓] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [✓] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [✓] If you have multiple commits please combine them into one commit by squashing them.

2020-09-20 08:48 UTC, jawidMuhammadi requested changes

2020-09-20 08:48 UTC, jawidMuhammadi commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java
> +                inputMethodManager.hideSoftInputFromWindow(drawerView.getWindowToken() , 0);
We already have defined a method called `hideKeyboard` in MifosBaseActivity, use that method instead.

2020-09-20 13:01 UTC, sachin-0102 reviewed
I thought it won't make a difference @jawidMuhammadi but it doesn't work that way on my device

2020-09-22 03:38 UTC, robustTechie commented
@sachin-0102 this issue is already fixed in #1521. So no need of sending a dublicate PR.

2020-09-22 03:40 UTC, robustTechie reviewed
@sachin-0102 this issue is already fixed in #1521. So no need of sending a duplicate PR :)

2020-09-22 03:43 UTC, sachin-0102 commented
Yes sir, I saw that

2020-09-22 03:43 UTC, closed without merging