Fixes #1562 UI improvements in client details page
openMF/android-client pull request #1563
Opened 2020-11-19 11:46 UTC by danishjamal104

Fixes #1562 

## Changes
* Added drawable `round_table_row_bg.xml` for rounded corners in a table row.
* Center aligned the image.
* Client name is now below the image instead of to the right.
* Added `Accounts` header to separate the client info table and accounts elements.
* Modified the padding and margin of account_accordion section

## Screenshot

<img width="335" alt="Screenshot 2020-11-19 at 5 10 13 PM" src="https://user-images.githubusercontent.com/31315800/99661678-33551700-2a8a-11eb-9f81-a3c077ed9f5c.png">

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-24 16:40 UTC, PatelVatsalB21 approved these changes
LGTM

2021-06-01 18:51 UTC, iamsh4shank requested changes
Can you fix the merge conflict so that we can merge it:)

2021-06-02 00:44 UTC, danishjamal104 commented
> Can you fix the merge conflict so that we can merge it:)

done with the changes, please check.

2021-06-02 06:19 UTC, iamsh4shank requested changes
Squash your commits as well

2021-06-04 01:54 UTC, danishjamal104 commented
@iamsh4shank kindly merge this. Thanks :)

2021-06-23 07:28 UTC, iamsh4shank approved these changes
LGTM

2021-06-23 07:32 UTC, iamsh4shank commented
@danishjamal104 can you fix the build fail so that I will merge it asap

2021-06-23 09:45 UTC, danishjamal104 commented
#### The build is passing successfully on my local machine but failing on the travis, see below two screen shot.

**Travis Screenshot of error**<br>
![Screenshot 2021-06-23 at 3 12 46 PM](https://user-images.githubusercontent.com/31315800/123075139-94d0d000-d435-11eb-8a21-b7a1a7b391f0.png)

**Local build screen shot of task:mifosng-android:pmd**<br>
![Screenshot 2021-06-23 at 3 13 05 PM](https://user-images.githubusercontent.com/31315800/123075162-97cbc080-d435-11eb-9e7c-3d9ecf895efa.png)

2021-06-23 15:13 UTC, iamsh4shank approved these changes
Yeah that's fine

2021-06-23 15:13 UTC, merged