Fixes #1577 Connectivity check added before fetching groups data
openMF/android-client pull request #1578
Opened 2020-11-26 21:51 UTC by danishjamal104

Fixes #1577 

## Screenshot
<img width="333" alt="Screenshot 2020-11-15 at 10 44 03 PM" src="https://user-images.githubusercontent.com/31315800/100393399-82d5ad00-305f-11eb-93c4-b3573050defb.jpg">

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-11-26 22:00 UTC, danishjamal104 commented
@robustTechie please review the changes

2020-11-26 22:16 UTC, robustTechie approved these changes
LGTM

2021-07-08 13:30 UTC, iamsh4shank approved these changes

2021-07-12 08:08 UTC, iamsh4shank requested changes
Hey @danishjamal104 can you fix the merge conflicts so that we could merge it soon :)

2023-06-20 17:33 UTC, closed without merging