Fixes #1584 Implemented auto toggle when network state changes.
openMF/android-client pull request #1585
Opened 2020-12-01 09:24 UTC by danishjamal104

Fixes #1584 

**Changes**
1. Implemented `NetworkChangeReceiver` broadcast receiver.
2. Registered the receiver in `DashboardActivity`.
3. Override `onNewIntent` method to toggle the app state from offline to online and vice versa.
4. Displays toast whenever auto switch takes place.

**Screenshot**
<img width="335" alt="Screenshot 2020-11-19 at 5 10 13 PM" src="https://user-images.githubusercontent.com/31315800/100720831-93ca4980-33e4-11eb-8aea-c3c4bacb4d4c.gif">

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-01 09:34 UTC, danishjamal104 commented
@robustTechie  pleases review the changes. Thanks :)

2020-12-01 15:01 UTC, robustTechie approved these changes
LGTM, Nice work @danishjamal104

2021-07-16 03:26 UTC, iamsh4shank requested changes
Hey @danishjamal104 can you fix the merge conflicts so that we could merge it soon :)

2021-07-17 15:02 UTC, iamsh4shank approved these changes

2023-06-20 13:59 UTC, Aditya-gupta99 commented
We are closing this PR as it causes a branch conflict since the Java file has now been migrated to kotlin

2023-06-20 17:33 UTC, closed without merging