Auto search added when user add filter in searchFragment
openMF/android-client pull request #1589
Opened 2020-12-03 08:17 UTC by danishjamal104

Fixes #1584 

**Changes**
* All changes are made in `SearchFragment.java` file.
1. Added new boolean variable `autoTriggerSearch` to determine whether a click is called by user or user this is used for determining whether a toast is needed to be displayed or not in case of the empty search string.
2. Called the `onClickSearch` inside `onItemSelected`

**Screenshot**
<img width="335" alt="Screenshot 2020-11-19 at 5 10 13 PM" src="https://user-images.githubusercontent.com/31315800/100981917-71176c80-356d-11eb-9b12-4ed4f08fa822.gif">

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-03 08:30 UTC, danishjamal104 commented
@robustTechie please review the changes And suggested if any. Thanks :)

2020-12-03 12:36 UTC, robustTechie approved these changes
Nice work @danishjamal104 👍

2020-12-04 15:16 UTC, danishjamal104 commented
> Nice work @danishjamal104 👍

Thanks @robustTechie :)

2021-07-17 14:56 UTC, iamsh4shank commented
Hey @danishjamal104 can you fix the merge request so that we could merge it soon :)

2021-07-17 14:56 UTC, iamsh4shank requested changes
Hey @danishjamal104 can you fix the merge request so that we could merge it soon :)

2021-07-17 14:57 UTC, danishjamal104 commented
> Hey @danishjamal104 can you fix the merge request so that we could merge it soon :)

Sure

2021-07-18 08:26 UTC, iamsh4shank approved these changes

2021-07-18 08:26 UTC, merged