Fix #1595: Corrected the Toast Message
openMF/android-client pull request #1599
Opened 2020-12-05 06:35 UTC by ritish099

Fixes #1595 

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

<img width="333" alt="alternative text" src="https://user-images.githubusercontent.com/54978105/101235854-0ba0b880-36f2-11eb-8f36-cec29f7ab4a2.jpg">

<img width="333" alt="alternative text" src="https://user-images.githubusercontent.com/54978105/101235856-0fccd600-36f2-11eb-8779-cba934d7340d.jpg">

2020-12-05 07:16 UTC, robustTechie requested changes

2020-12-05 07:16 UTC, robustTechie commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/online/checkerinbox/CheckerInboxFragment.kt
> +                            "Rejected")
It would be great if you use string resources for this :)

2020-12-05 07:16 UTC, robustTechie commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/online/checkerinbox/CheckerInboxFragment.kt
> +                            "Deleted")
Here too

2020-12-05 13:57 UTC, ritish099 commented
@robustTechie Check it out...

2020-12-05 14:41 UTC, danishjamal104 requested changes

2020-12-05 14:41 UTC, danishjamal104 commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/online/checkerinbox/CheckerInboxFragment.kt
> +        Toast.makeText(activity, getString(R.string.entry) + " " + action, Toast.LENGTH_SHORT).show()
Use string formatter and declare a variable which contains the toastier message instead of passing it directly and using string concatenation.

2020-12-05 14:41 UTC, danishjamal104 commented on mifosng-android/src/main/res/values/strings.xml
> +    <string name="rejected">Rejected</string>
Add the translations string also for all the three new strings

2020-12-05 17:09 UTC, ritish099 commented
@danishjamal104 Kindly check it out...

2020-12-05 18:07 UTC, ritish099 commented
@danishjamal104 Please check it out....

2020-12-05 19:40 UTC, danishjamal104 approved these changes
Nice work @ritish099 .
Everything LGTM.

2020-12-06 08:21 UTC, robustTechie approved these changes
LGTM

2023-06-15 12:03 UTC, closed without merging