Feat #1343: Added new feature of generating PDF from Saving Account Summary
openMF/android-client pull request #1602
Opened 2020-12-06 12:30 UTC by PatelVatsalB21

Feat #1343 
Added new feature of generating PDF from Saving Account Summary. It askes for
**read and write permissions** and also checks for permission before making pdf then it  generates PDF in **Mifos Docs** directory in internal storage with file name as client name.

**Generating PDF**
![GIF-201206_173254](https://user-images.githubusercontent.com/70195106/101279924-e85a3400-37eb-11eb-8b76-381b29a1154b.gif)

**Looking for PDF in storage**
![GIF-201206_173718](https://user-images.githubusercontent.com/70195106/101279994-5e5e9b00-37ec-11eb-8c36-230c99713ad2.gif) 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-06 13:20 UTC, PatelVatsalB21 commented
@robustTechie please check this new feature. Once build failed then i pushed again but now build didn't started.

2020-12-06 13:45 UTC, robustTechie commented
Can you again make some changes and then resend the PR?

2020-12-06 15:28 UTC, PatelVatsalB21 commented
@robustTechie what kind of changes do you prefer. I will make pr again then.

2020-12-06 18:05 UTC, danishjamal104 requested changes
Hey @PatelVatsalB21 , right now you are first saving the screenshot as `miffos_img.jpg`
and then generating a pdf using the file, I think that this method is less efficient, since your end goal is to save pdf then why are you saving img and then generating pdf then deleting that image. 
Better solution can be implementing the direct approach to generate pdf.


Also will the pdf be of multi page, as transactions in one saving can be large to not fit in one SS.

2020-12-06 18:17 UTC, PatelVatsalB21 commented
@danishjamal104  I got what you are saying, but making PDF directly needs text to be formatted in tabular form that would be more lenthy and harcoded as a string and then needs to be written. So I took this approach. I am working for long screenshot but as I saw transactions were limited to 5. I am working on that feature too :)

2020-12-07 23:15 UTC, robustTechie commented
@PatelVatsalB21 I agree with @danishjamal104 you need to create a pdf so that all the information can be kept in that pdf :)

2020-12-08 14:11 UTC, closed without merging