Fixes #1610 InstanceURl edit preference added in settings
openMF/android-client pull request #1612
Opened 2020-12-09 12:35 UTC by danishjamal104

Fixes #1610  

<img width='333' alt='ss-2' src='https://user-images.githubusercontent.com/31315800/101630197-8ba78500-3a48-11eb-915d-338107f4e998.jpeg'> | <img width='333' alt='ss-1' src='https://user-images.githubusercontent.com/31315800/101630203-8e09df00-3a48-11eb-9b00-1f6dc10d73db.jpeg'>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-09 12:43 UTC, danishjamal104 commented
@robustTechie please review the changes. thanks :)

2020-12-10 14:38 UTC, robustTechie commented
Hey, @danishjamal104 how about adding the passcode verification just before changing the Instance URL ?

2020-12-10 17:12 UTC, robustTechie reviewed
Hey, @danishjamal104 how about adding the passcode verification just before changing the Instance URL ?

2020-12-10 17:32 UTC, danishjamal104 commented
> Hey, @danishjamal104 how about adding the passcode verification just before changing the Instance URL ?

I am not able to get the actual idea of how things are related. Like what's the difference between domain and instance and the changes that I made only updates the sharedPref using Prefmanager as you can. see in changes. I wasn't clear about it that's why I didn't applied passcode functionality.
So please help me with that.

2020-12-13 20:24 UTC, robustTechie commented
Yeah, so you can something like if the user clicks on change instance thing then it will ask the user to enter the passcode then allows to change the URL

2021-07-08 13:48 UTC, iamsh4shank approved these changes

2021-07-12 08:09 UTC, iamsh4shank commented
@danishjamal104 any update on this?

2021-07-12 10:41 UTC, danishjamal104 commented
> @danishjamal104 any update on this?

I think passcode isn't required while changing the instance URL, because its more of a administration thing, and while starting the app also user has option to change the domain, port, and tenant which is before setting password.

2021-07-13 04:58 UTC, iamsh4shank requested changes

2021-07-13 04:58 UTC, iamsh4shank commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/SettingsFragment.kt
> +        mInstanceUrlPref!!.dialogTitle = "Edit Instance Url"
It would be great if you could change this hardcoded string into string resources :)

2021-07-16 03:28 UTC, iamsh4shank requested changes
Hwy @danishjamal104 can you fix the requested changes as well as merge conflicts so that we could merge it soon :)

2021-07-17 15:06 UTC, iamsh4shank approved these changes

2021-07-20 05:55 UTC, merged