Fixes #1614 Intro added in SearchFragment
openMF/android-client pull request #1616
Opened 2020-12-11 11:14 UTC by danishjamal104

Fixes #1614 

<img width='333' alt='ss1' src='https://user-images.githubusercontent.com/31315800/101896878-ab1cea00-3bcf-11eb-9a1b-7843ab129d31.jpeg'> | <img width='333' alt='ss1' src='https://user-images.githubusercontent.com/31315800/101896892-b112cb00-3bcf-11eb-8f92-d26e9996f33e.jpeg'> | <img width='333' alt='ss1' src='https://user-images.githubusercontent.com/31315800/101896896-b1ab6180-3bcf-11eb-8869-111d67724299.jpeg'> | <img width='333' alt='ss1' src='https://user-images.githubusercontent.com/31315800/101896897-b243f800-3bcf-11eb-9796-8dbe7fedb51d.jpeg'>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-11 11:23 UTC, danishjamal104 commented
@robustTechie please review the changes. Thanks :)

2020-12-13 20:22 UTC, robustTechie approved these changes
LGTM

2021-07-08 15:10 UTC, iamsh4shank requested changes
@danishjamal104 can you fix the merge conflicts so that we can merge the PR :)

2021-07-12 04:29 UTC, iamsh4shank approved these changes

2021-07-13 05:10 UTC, merged