Fixes #1647 UI redesign of client identifier list item
openMF/android-client pull request #1650
Opened 2020-12-19 21:05 UTC by danishjamal104

Fixes #1647 

* Green color represents `active`.
* Red color represents `inactive`.

Before | After
--|--
<img width='333' alt='ss1' src='https://user-images.githubusercontent.com/31315800/102699555-a3aeae00-426b-11eb-84de-4dea2e3479a7.jpeg'> | <img width='333' alt='ss1' src='https://user-images.githubusercontent.com/31315800/102699557-a6a99e80-426b-11eb-85b8-2d14007b28f5.jpeg'>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-24 15:29 UTC, PatelVatsalB21 approved these changes
LGTM

2021-06-01 18:53 UTC, iamsh4shank requested changes
Can you fix the merge conflict so that we can merge it:)

2021-06-02 00:44 UTC, danishjamal104 commented
> Can you fix the merge conflict so that we can merge it:)

done with the changes, please check.

2021-06-02 06:20 UTC, iamsh4shank requested changes
Squash your commits as well

2021-06-03 05:06 UTC, danishjamal104 commented
> Squash your commits as well

I am not able to figure out, how to squash. Since the two commits has huge time gap. Their are more than 30 commits between them.

2021-06-04 01:53 UTC, danishjamal104 commented
Kindly merge this. Thanks :)

2021-06-23 07:23 UTC, iamsh4shank approved these changes
LGTM

2021-06-23 07:30 UTC, merged