Fixes #I1690 Transaction details layout added
openMF/android-client pull request #1695
Opened 2020-12-30 18:25 UTC by danishjamal104

Fixes #I1690

<img width='333' alt='ss' src='https://user-images.githubusercontent.com/31315800/103373217-57306180-4afa-11eb-87f8-7c748fb34eb1.jpeg'>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-12-31 16:44 UTC, PatelVatsalB21 commented
@danishjamal104 please remove typo from heading rest all looks good :)

2021-01-09 18:32 UTC, PatelVatsalB21 approved these changes
LGTM

2021-07-08 13:37 UTC, iamsh4shank approved these changes

2021-07-12 04:36 UTC, iamsh4shank requested changes
Hey @danishjamal104 can you fix the merge conflicts so that we could merge it soon :)

2021-07-13 05:11 UTC, merged