Fixed Home Activity fragment transactions
openMF/android-client pull request #1907
Opened 2023-03-01 08:20 UTC by Aditya-gupta99

Fixes #1906 

https://user-images.githubusercontent.com/94394661/222082816-3b13608b-04cc-4929-a549-74bf34b8ec32.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2023-03-20 04:55 UTC, Aditya-gupta99 commented
@avinash14022002 Now the PR has been separated, please review it.

2023-06-06 04:13 UTC, avinash14022002 commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/HomeActivity.kt
> +    private var mCount = 1
@Aditya-gupta99 ,
please use proper naming convention

2023-06-06 04:13 UTC, avinash14022002 requested changes
Do the changes

2023-06-08 03:57 UTC, avinash14022002 commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/HomeActivity.kt
> +            doubleBackToExit()
@Aditya-gupta99 ,
please check why lint and Pretier didn't detect that?

2023-06-08 03:58 UTC, avinash14022002 requested changes
please do the needful changes

2023-06-23 20:14 UTC, Aditya-gupta99 commented
We're closing this PR since it's already fixed

2023-07-06 17:03 UTC, closed without merging