Dialog design has been improved
openMF/android-client pull request #1947
Opened 2023-04-24 20:25 UTC by Aditya-gupta99

Fixes #1900 

https://user-images.githubusercontent.com/94394661/234108301-a02124c5-92c8-4b22-9ef0-3f4eea9d703e.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2023-04-24 20:36 UTC, Aditya-gupta99 commented
Replacing PR #1901 with this one.

2023-04-24 20:37 UTC, Aditya-gupta99 commented
@avinash14022002 Please review this PR.

2023-06-06 04:28 UTC, avinash14022002 commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseActivity.java
> +
adding extra line change in codebase please keep it as it

2023-06-06 04:30 UTC, avinash14022002 requested changes
please do the needful changes

2023-06-06 04:30 UTC, avinash14022002 commented
> please do the needful changes

@Aditya-gupta99 
solve the merge conflict

2023-06-06 19:13 UTC, closed without merging