feat: upgrade gradle groovy to kotlin dsl
openMF/android-client pull request #2062
Opened 2024-02-02 14:59 UTC by Aditya-gupta99

Fixes #2061 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2024-02-02 18:28 UTC, Aditya-gupta99 commented
@therajanmaurya Can you please review this PR.

2024-02-03 14:28 UTC, therajanmaurya requested changes

2024-02-03 14:28 UTC, therajanmaurya commented on mifosng-android/src/main/AndroidManifest.xml
> +    <!--    package="com.mifos.mifosxdroid">-->
remove this we don't need this

2024-02-03 14:28 UTC, therajanmaurya commented on mifosng-android/src/main/AndroidManifest.xml
> -<!--            android:value="facae47316396ae7954149cc408e25b7a37ab7ea" />-->
Open an issue to implement the firebase inplace of fabric, upgrade fabric to firebase

2024-02-03 18:41 UTC, Aditya-gupta99 commented
@therajanmaurya I have done the required changes

2024-02-07 12:09 UTC, therajanmaurya approved these changes

2024-02-07 12:09 UTC, merged