Refactor: Migrate SearchFragment to Jetpack Compose
openMF/android-client pull request #2073
Opened 2024-02-29 07:12 UTC by ashutosh-kumar-kushwaha

Fixes #2066

https://github.com/openMF/android-client/assets/109234707/1f60fa86-0866-456f-bc2c-abb777c6e0d5

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2024-04-07 22:01 UTC, therajanmaurya commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/views/MultiFloatingActionButton.kt
> +package com.mifos.mifosxdroid.views
Good Implementation

2024-05-10 06:06 UTC, Aditya-gupta99 commented
@ashutosh-kumar-kushwaha Can you make the changes listed above so that we can merge this PR?

2024-05-10 19:38 UTC, ashutosh-kumar-kushwaha commented
> @ashutosh-kumar-kushwaha Can you make the changes listed above so that we can merge this PR?

I have resolved the merge conflicts. Please let me know if anything else is required.

2024-05-12 17:47 UTC, Aditya-gupta99 commented
@ashutosh-kumar-kushwaha Can do the changes which i have mentioned so that we can merge this PR.

2024-05-12 19:21 UTC, Aditya-gupta99 requested changes
@ashutosh-kumar-kushwaha Can you make the changes listed so that we can merge this PR?

2024-05-12 19:21 UTC, Aditya-gupta99 commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/online/search/SearchScreen.kt
> +    val searchUiState = viewModel.searchUiState.collectAsState().value
use collectAsStateWithLifecycle instead collectAsState
Add below dependency
implementation("androidx.lifecycle:lifecycle-runtime-compose:2.7.0")
`val searchUiState = viewModel.searchUiState.collectAsStateWithLifecycle().value`

2024-05-12 19:21 UTC, Aditya-gupta99 commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/online/search/SearchScreen.kt
> +                            contentColor = MaterialTheme.colorScheme.onSurface
Use mifos Color scheme .You will get inside designsystem module color file

2024-05-12 19:21 UTC, Aditya-gupta99 commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/online/search/SearchScreen.kt
> +    Dialog(onDismissRequest = onDismissRequest) {
Don't use dialog instead of that use CircularProgressIndicator

2024-05-19 16:06 UTC, therajanmaurya commented
I see when we click on Search EditText, View move below little bit fix that please.

2024-12-04 14:14 UTC, closed without merging