refactor: refactor Center details fragment to compose
openMF/android-client pull request #2112
Opened 2024-06-16 18:03 UTC by Aditya-gupta99

Jira [MIFOSAC-171](https://mifosforge.jira.com/browse/MIFOSAC-171)

<center>
    <table>
        <tr>
            <td align="center" valign="center">
<br><center>XML Screen</center>
<video src="https://github.com/openMF/android-client/assets/94394661/67131dfb-1d67-4813-a664-fa832e57e272"> 
            </td>
            <td align="center" valign="center">
<br><center>Jetpack Compose</center>
<video src="https://github.com/openMF/android-client/assets/94394661/e16e9f2e-8ace-4ac4-b3cc-531124f44189">                 
            </td>
        </tr>
    </table>
</center>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2024-06-18 12:02 UTC, AdityaKumdale commented
Looks good to me.

2024-06-18 14:05 UTC, therajanmaurya requested changes

2024-06-18 14:05 UTC, therajanmaurya commented on feature/center/src/main/java/com/mifos/feature/center/center_details/CenterDetailsScreen.kt
> +            TopAppBar(
Why this is not part of designsystem

2024-06-19 17:52 UTC, Aditya-gupta99 commented on feature/center/src/main/java/com/mifos/feature/center/center_details/CenterDetailsScreen.kt
> +            TopAppBar(
Resolved

2024-06-19 17:54 UTC, merged