Applied Spotless and Detekt to the "feature-datatable" module. MIFOSAC-282
openMF/android-client pull request #2256
Opened 2024-12-07 17:47 UTC by Aditya3815

Apply Spotless and Detekt to the "feature-datatable" module.

Fixes https://mifosforge.jira.com/browse/MIFOSAC-282

Please Add Screenshots If there are any UI change
![Screenshot 2024-12-07 225832](https://github.com/user-attachments/assets/a83e06b7-1c7b-478a-a1fb-52399483f76f)
![Screenshot 2024-12-07 225909](https://github.com/user-attachments/assets/82cb1b71-f567-4a7e-808d-76d74c625318)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-12-08 04:06 UTC, Aditya3815 commented
Sir, please merge this PR this is done

2024-12-08 08:01 UTC, itsPronay commented
@Aditya3815 please fix merge conflicts

2024-12-12 09:44 UTC, itsPronay requested changes

2024-12-12 09:44 UTC, itsPronay commented on feature/data-table/src/main/java/com/mifos/feature/dataTable/dataTable/DataTableScreen.kt
> +            modifier = modifier // Pass the modifier here
can you remove comments here?

2024-12-12 09:44 UTC, itsPronay commented on feature/data-table/src/main/java/com/mifos/feature/dataTable/dataTableData/DataTableDataScreen.kt
> +        Column(modifier = modifier.padding(paddingValues)) { // Use the passed Modifier here
here as well

2024-12-12 13:51 UTC, Aditya3815 commented
Sure



On Thu, Dec 12, 2024 at 3:14 PM Pronay Sarker ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> feature/data-table/src/main/java/com/mifos/feature/dataTable/dataTable/DataTableScreen.kt
> <https://github.com/openMF/android-client/pull/2256#discussion_r1881725756>
> :
>
> >      ) {
>          Box(
> -            modifier = Modifier
> +            modifier = modifier // Pass the modifier here
>
> can you remove comments here?
> ------------------------------
>
> In
> feature/data-table/src/main/java/com/mifos/feature/dataTable/dataTableData/DataTableDataScreen.kt
> <https://github.com/openMF/android-client/pull/2256#discussion_r1881727560>
> :
>
> >      ) { paddingValues ->
> -        Column(modifier = Modifier.padding(paddingValues)) {
> +        Column(modifier = modifier.padding(paddingValues)) { // Use the passed Modifier here
>
> here as well
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openMF/android-client/pull/2256#pullrequestreview-2498640986>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUGJNUXW2HPM7IBR3YBOIGD2FFLILAVCNFSM6AAAAABTGM6BQWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJYGY2DAOJYGY>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-12-12 16:45 UTC, merged