Survey-Question-Logic-Implemented
openMF/android-client pull request #2262
Opened 2024-12-09 07:25 UTC by sujalagrawal2

Fixes [JIRA](https://mifosforge.jira.com/jira/software/c/projects/MIFOSAC/issues/MIFOSAC-292?filter=allissues&jql=project%20%3D%20%22MIFOSAC%22%20ORDER%20BY%20created%20DESC)

Please Add Screenshots If there are any UI changes.

https://github.com/user-attachments/assets/ba19ca1f-4082-44ec-8edd-561660d6b3f0

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-12-09 18:13 UTC, itsPronay commented on feature/client/src/main/java/com/mifos/feature/client/clientSurveyQuestion/SurveyQuestionScreen.kt
> +    queViewModel: SurveyQuestionViewModel = hiltViewModel(),
submitViewmodel
quesViewmodel / questionViewmodel

2024-12-09 18:14 UTC, itsPronay commented on feature/client/src/main/java/com/mifos/feature/client/clientSurveyQuestion/SurveyQuestionScreen.kt
>      val uiState by viewModel.surveySubmitUiState.collectAsStateWithLifecycle()
choose an appropriate name, don't just do uiState , uiState2. its confusing,

2024-12-09 18:29 UTC, itsPronay commented on feature/client/src/main/java/com/mifos/feature/client/clientSurveyQuestion/SurveyQuestionScreen.kt
> +    id: Int,
dont pass `id` in here, retrieve it from viewmodel.

2024-12-30 18:41 UTC, itsPronay commented
@sujalagrawal2 checks are failing. can you fix them?

2025-01-01 05:28 UTC, sujalagrawal2 commented
@itsPronay checks have been fixed. Please review.

2025-01-02 11:01 UTC, itsPronay commented
> @itsPronay checks have been fixed. Please review.

@sujalagrawal2 still not fixed. Run 
`./gradlew spotlessApply` and ../gradlew detekt` after pulling the changes

2025-01-04 17:53 UTC, sujalagrawal2 commented
@itsPronay please review

2025-01-06 19:19 UTC, itsPronay commented on feature/client/src/main/java/com/mifos/feature/client/navigation/ClientScreens.kt
> +    data object ClientSurveyQuestionScreen : ClientScreens("client_survey_question_screen/{${Constants.CLIENT_ID}}") {
client ID? shouldn't this be survey_id !?

2025-01-06 19:21 UTC, itsPronay commented on feature/client/src/main/java/com/mifos/feature/client/clientSurveyQuestion/SurveyQuestionViewModel.kt
> +    val surveyId = savedStateHandle.getStateFlow(key = Constants.CLIENT_ID, initialValue = -1)
set initial to 0

2025-01-06 19:26 UTC, itsPronay commented on feature/client/src/main/java/com/mifos/feature/client/navigation/ClientScreens.kt
> +    }
client ID? shouldn't this be survey_id !?

2025-01-06 19:35 UTC, Darkeye14 commented on core/data/src/main/java/com/mifos/core/data/repository/SurveyQuestionRepository.kt
> +    fun getSurvey(surveyId: Int): Observable<Survey>
@itsPronay bhai, what do you say about using Flow instead of Observables???

2025-01-06 19:35 UTC, Darkeye14 commented on feature/client/src/main/java/com/mifos/feature/client/navigation/ClientScreens.kt
> +    }
Nahi bhai, I think clientid id correct??? We are taking the survey for that particular client right??

2025-01-06 19:35 UTC, Darkeye14 commented on core/data/src/main/java/com/mifos/core/data/repositoryImp/SurveyQuestionRepositoryImp.kt
> +    override fun getSurvey(surveyId: Int): Observable<Survey> {
same here!

2025-01-06 19:44 UTC, itsPronay commented on feature/client/src/main/java/com/mifos/feature/client/navigation/ClientScreens.kt
> +    }
@Darkeye14 Correct me if I am wrong, but on line 49 we are passing surveyId right?? Even in the ViewModel, we are retrieving that value and storing it in the surveyId variable. however on line 48, it says Client_ID

Shouldn’t both be the same!?!

2025-01-06 19:45 UTC, itsPronay commented on feature/client/src/main/java/com/mifos/feature/client/navigation/ClientScreens.kt
> +    }
yea in my opinion both be the same.. either survey_id or client_id depending on what we are passing

2025-01-06 20:16 UTC, Darkeye14 approved these changes

2025-01-06 20:16 UTC, Darkeye14 commented on feature/client/src/main/java/com/mifos/feature/client/navigation/ClientScreens.kt
> +    }
nahi bhai, i think this is correct!!

2025-01-06 20:16 UTC, Darkeye14 commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/components/Navigation.kt
> +                val id: Int = survey[position].id
theres no need to explicitly specify the data type, i think. just a suggestion tho.

2025-01-06 20:16 UTC, Darkeye14 commented on core/data/src/main/java/com/mifos/core/data/repository/SurveyQuestionRepository.kt
> +    fun getSurvey(surveyId: Int): Observable<Survey>
ha bhai

2025-01-06 20:17 UTC, itsPronay commented on mifosng-android/src/main/java/com/mifos/mifosxdroid/components/Navigation.kt
> +                val id: Int = survey[position].id
+ @sujalagrawal2 replace id with clientId

2025-01-06 20:31 UTC, itsPronay commented on feature/client/src/main/java/com/mifos/feature/client/navigation/ClientScreens.kt
> +    }
oh... my apologies. I didn't see we are using 2 view models here.

2025-01-07 10:48 UTC, sujalagrawal2 commented
@itsPronay Done the changes.

2025-01-07 16:04 UTC, itsPronay approved these changes
looks good to me

2025-01-07 16:39 UTC, niyajali requested changes

2025-01-07 16:39 UTC, niyajali commented on feature/client/src/main/java/com/mifos/feature/client/clientSurveyQuestion/SurveyQuestionScreen.kt
> +        questionViewModel.loadSurvey(surveyId)
Instead calling viewModel fun directly inside of a composable using effect handler, we can call in ViewModel using ` init{}` block.

2025-01-07 19:17 UTC, sujalagrawal2 commented
@niyajali please review

2025-01-30 22:13 UTC, therajanmaurya commented
Closing it, not mergeable PR

2025-01-30 22:13 UTC, closed without merging