refactor: moving files from database module to model module
openMF/android-client pull request #2275
Opened 2024-12-27 10:46 UTC by Darkeye14

Fixes [JIRA](https://mifosforge.jira.com/jira/software/c/projects/MIFOSAC/issues/MIFOSAC-321?jql=project%20%3D%20%22MIFOSAC%22%20ORDER%20BY%20created%20DESC)

https://github.com/user-attachments/assets/c8739ed7-7eab-4505-ae33-e0e490c7274d

2024-12-27 19:32 UTC, itsPronay commented
@Darkeye14 There are classes like `Loan`, `Loans`, and `CenterAccounts` that are not annotated with @ModelContainer and yet they are still part of the database module. Could you please clarify!

2024-12-28 13:06 UTC, niyajali requested changes

2024-12-28 13:08 UTC, niyajali commented on core/data/src/main/java/com/mifos/core/data/pagingSource/CenterListPagingSource.kt
> +import com.mifos.core.modelobjects.clients.Page
And see why we need object package inside of the model module, can we move the files directly to the module

2024-12-28 17:23 UTC, Darkeye14 commented on core/data/src/main/java/com/mifos/core/data/pagingSource/CenterListPagingSource.kt
> +import com.mifos.core.modelobjects.clients.Page
> And see why we need object package inside of the model module, can we move the files directly to the module

bhaiya that can be done but the ServerConfig file doesnt belong with the other objects so i made another package named objects.

2024-12-28 17:24 UTC, Darkeye14 commented
> @Darkeye14 There are some classes like `Loan`, `Loans`, `CenterAccounts` etc that are not annotated with @ModelContainer and yet they are still part of the database module. Could you please clarify!
> 
> ![image](https://private-user-images.githubusercontent.com/78101731/399001747-092d14a5-f7dd-4ffd-91de-43e9a0438820.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MDY5MzMsIm5iZiI6MTczNTQwNjYzMywicGF0aCI6Ii83ODEwMTczMS8zOTkwMDE3NDctMDkyZDE0YTUtZjdkZC00ZmZkLTkxZGUtNDNlOWEwNDM4ODIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDE3MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NDBjOTcwYjE0OTY3N2Q3ZDdlY2I0YWNlNWUyMTljNzUyYWQ1ODlhZmFhNDFlZGJlNjM2NGFlOTk0ZDY5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5oCxhskLe72jFuURC8hm8-104WfRZE-TEDlnXwQQP5c)

Bhai, ive explained it on slack bhai

2024-12-28 17:32 UTC, niyajali commented on core/data/src/main/java/com/mifos/core/data/pagingSource/CenterListPagingSource.kt
> +import com.mifos.core.modelobjects.clients.Page
Okay no issues, seems like static analysis build is failing, fix that and I'll open your PR on IDE for better understanding.

2024-12-28 17:47 UTC, Darkeye14 commented on core/data/src/main/java/com/mifos/core/data/pagingSource/CenterListPagingSource.kt
> +import com.mifos.core.modelobjects.clients.Page
bhaiya dont merge it yet, it will break down as of now

2024-12-28 17:48 UTC, Darkeye14 commented on core/data/src/main/java/com/mifos/core/data/pagingSource/CenterListPagingSource.kt
> +import com.mifos.core.modelobjects.clients.Page
> Okay no issues, seems like static analysis build is failing, fix that and I'll open your PR on IDE for better understanding.

ha bhaiya!

2025-01-06 16:46 UTC, therajanmaurya commented
@niyajali Review

2025-01-06 19:33 UTC, niyajali requested changes

2025-01-06 19:33 UTC, niyajali commented on core/network/src/main/java/com/mifos/core/network/mappers/centers/CenterMapper.kt
> +import com.mifos.core.dbobjects.group.Center
Rename `dbobject` package to `model`

2025-01-06 19:33 UTC, niyajali commented on core/database/src/main/java/com/mifos/core/data/LoansPayload.kt
> +import com.mifos.core.dbobjects.noncore.DataTablePayload
Move this files in network model package and why we need payload in database module if you needed that data class than rename to LoanEntity

2025-01-06 19:34 UTC, niyajali commented on core/network/src/main/java/com/mifos/core/network/mappers/centers/CenterMapper.kt
> +import com.mifos.core.dbobjects.group.Center
Or `entity`

2025-01-07 12:41 UTC, Darkeye14 commented on core/database/src/main/java/com/mifos/core/data/LoansPayload.kt
> +import com.mifos.core.dbobjects.noncore.DataTablePayload
Ha bhaiya, ive moved it to network module and the rest of them are moved to model module.

2025-01-07 12:44 UTC, Darkeye14 commented on core/network/src/main/java/com/mifos/core/network/mappers/centers/CenterMapper.kt
> +import com.mifos.core.dbobjects.group.Center
ha bhaiya, entity kardunga

2025-01-08 16:53 UTC, merged