KMP dependencies setup
openMF/android-client pull request #2277
Opened 2024-12-31 16:59 UTC by itsPronay

Fixes [JIRA](https://mifosforge.jira.com/browse/MIFOSAC-323)

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-12-31 18:08 UTC, biplab1 commented on gradle/libs.versions.toml
> +ktrofit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
Change "ktrofit" to "ktorfit"

2025-01-01 16:42 UTC, niyajali requested changes

2025-01-01 16:42 UTC, niyajali commented on core/model/lint-baseline.xml
> +    If a copy of the MPL was not distributed with this file,
Remove this file

2025-01-01 16:42 UTC, niyajali commented on core/designsystem/build.gradle.kts
> +    stabilityConfigurationFile = rootProject.layout.projectDirectory.file("compose_compiler_config.conf")
and why we are applying stability configuration in here and other build files instead apply on `build-logic/AndroidCompose.kt` file and their we already applied I think.

2025-01-01 16:42 UTC, niyajali commented on build-logic/convention/src/main/kotlin/org/mifos/configureKotlinMultiplatform.kt
> +
Change the File name to KotlinMultiplatform.kt

2025-01-01 16:42 UTC, niyajali commented on build-logic/convention/src/main/kotlin/KMPLibraryConventionPlugin.kt
> + * Created by Pronay Sarker on 30/12/2024 (7:33 PM)
Please Remove your copyright. We've applied the ORG license/copyright notice in the project and many other things will be applied soon, and you should not use your copyright and violate the policy. FYI your commit history never delete so don't worry your hard work always remains

2025-01-02 15:06 UTC, niyajali approved these changes
Looks good to me, could be merged

2025-01-06 16:45 UTC, merged